---

#- hosts: spine
#  roles:
#    - role: spine

- hosts: n9k_spine
  roles:
    - role: n9k_spine

- hosts: n7k_spine
  roles:
    - role: n7k_spine

- hosts: leaf
  roles:
    - role: leaf

#- hosts: all
  #tasks:
  #  - name: save config
  #    nxos_save_config: host={{ inventory_hostname }}

#- include: switches.yml
